# Branch Protection Rules for Valvex Repository
# This file defines security rules for the main branch

branch-protection:
  main:
    required_status_checks:
      strict: true
      contexts:
        - "security-scan"
        - "deploy"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    restrictions:
      users: []
      teams: []
    allow_force_pushes: false
    allow_deletions: false
