# GitHub Secret Scanning Configuration
# This file configures secret scanning for the repository

secret-scanning:
  enabled: true
  patterns:
    - "shpat_*"
    - "sk_*"
    - "pk_*"
    - "ghp_*"
    - "gho_*"
    - "ghu_*"
    - "ghs_*"
    - "ghr_*"
