name: Deploy Valvex Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Security scan
      run: |
        echo "Running security scan..."
        # Check for exposed secrets
        if grep -r "shpat_" . --exclude-dir=.git; then
          echo "Warning: Potential secret detected"
          exit 1
        fi
        echo "Security scan passed"
        
  deploy:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Configure environment
      run: |
        echo "SHOPIFY_TOKEN=${{ secrets.SHOPIFY_TOKEN }}" >> $GITHUB_ENV
        echo "Environment configured with GitHub Secrets"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        
    - name: Security notification
      run: |
        echo "Deployment completed with GitHub Secrets"